CREATE TABLE IF NOT EXISTS person (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    dateNaissance DATE DEFAULT (CURRENT_DATE()),
    ville VARCHAR(100) NOT NULL,
    nombreEnfants INT DEFAULT 0,
    investissement BOOLEAN DEFAULT FALSE,
    placement BOOLEAN DEFAULT FALSE,
    situationFamiliale ENUM("CELIBATAIRE", "MARIE", "VEUF"),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    score INT DEFAULT 0,
    role ENUM("employé", "professionnel") DEFAULT "employé"
);

CREATE TABLE IF NOT EXISTS employe (
    id INT AUTO_INCREMENT PRIMARY KEY,
    salaire DECIMAL(10, 2) NOT NULL,
    anciennete INT NOT NULL,
    poste VARCHAR(100) NOT NULL,
    typeContrat VARCHAR(255) NOT NULL,
    secteur ENUM("PUBLIC", "GRANDE_ENTREPRISE", "PME") NOT NULL,
    FOREIGN KEY (id) REFERENCES person(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS professionnel (
    id INT AUTO_INCREMENT PRIMARY KEY,
    revenu DECIMAL(10, 2) NOT NULL,
    immatriculationFiscale DECIMAL(10, 2) NOT NULL,
    secteurActivite VARCHAR(255) NOT NULL,
    Activite VARCHAR(255) NOT NULL,
    FOREIGN KEY (id) REFERENCES person(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS credit (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dateCredit TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    montantDemande DECIMAL(10, 2) NOT NULL,
    montantOctroye DECIMAL(10, 2) NOT NULL,
    tauxInteret DECIMAL(6, 6) NOT NULL,
    dureeenMois INT NOT NULL,
    typeCredit VARCHAR(255) NOT NULL,
    decision ENUM("ACCORDIMMEDIAT", "ETUDEMANUELLE", "REFUS_AUTOMATIQUE"),
    person_id INT NOT NULL,
    FOREIGN KEY (person_id) REFERENCES person(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS echeance (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dateEcheance TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    mensualite DECIMAL(10, 2) NOT NULL,
    datePaiement TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    statutPaiement ENUM("PAYEATEMPS", "ENRETARD", "PAYEENRETARD", "IMPAYENONREGLE", "IMPAYEREGLE"),
    credit_id INT NOT NULL,
    FOREIGN KEY (credit_id) REFERENCES credit(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS incident (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dateIncident TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    score INT NOT NULL,
    typeIncident ENUM("PAYEATEMPS", "ENRETARD", "PAYEENRETARD", "IMPAYENONREGLE", "IMPAYEREGLE"),
    echeance_id INT NOT NULL,
    FOREIGN KEY (echeance_id) REFERENCES echeance(id) ON DELETE CASCADE
);